title: Alliance Information
description: A comprehensive guide to our Last Z Survival Shooter alliance
show_downloads: false

baseurl: "/Alliance-Information"
url: "https://boblzsurvivor-wq.github.io"

theme: slate
#remote_theme: remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
