title: Alliance Information
description: A comprehensive guide to our Last Z Survival Shooter alliance

baseurl: "/Alliance-Information"
url: "https://boblzsurvivor-wq.github.io"

remote_theme: theoremoon/jekyll-text-theme

plugins:
  - jekyll-remote-theme
